set local lock_timeout = '5s';

create table public.consejos_diarios (
  id smallint primary key check (id > 0),
  categoria text not null check (categoria in ('trabajo', 'vida_personal', 'finanzas', 'aprendizaje', 'habitos')),
  consejo text not null unique check (char_length(btrim(consejo)) between 30 and 240)
);

comment on table public.consejos_diarios is
  'Consejos breves de contenido público para la tarjeta previa al inicio de sesión. La aplicación mezcla el catálogo por ciclos y mantiene un consejo por fecha de Costa Rica.';

alter table public.consejos_diarios enable row level security;
revoke all on table public.consejos_diarios from public, anon, authenticated;
grant select on table public.consejos_diarios to anon, authenticated;

create policy consejos_diarios_lectura_publica
  on public.consejos_diarios for select to anon, authenticated
  using (true);
insert into public.consejos_diarios (id, categoria, consejo) values
  (1, 'trabajo', 'Antes de empezar a trabajar, elige la tarea más importante del día y dale un lugar en tu horario.'),
  (2, 'trabajo', 'Si una tarea parece muy grande, divídela en pasos pequeños y comienza por el primero.'),
  (3, 'trabajo', 'Si una instrucción no está clara, pregunta antes de empezar. Una pregunta a tiempo evita trabajo doble.'),
  (4, 'trabajo', 'Cuando recibas una tarea, confirma qué hay que entregar y para cuándo.'),
  (5, 'trabajo', 'Devuelve las herramientas a su lugar al terminar. La próxima persona también necesita encontrarlas.'),
  (6, 'trabajo', 'Al cambiar de turno, deja claro qué quedó listo y qué necesita seguimiento.'),
  (7, 'trabajo', 'Cuando trabajen varias personas en una tarea, acuerden quién se encarga de cada parte.'),
  (8, 'trabajo', 'Antes de prometer una fecha, revisa cuánto trabajo tienes pendiente.'),
  (9, 'trabajo', 'Prepara con tiempo lo que necesitas para llegar al trabajo sin tantas carreras.'),
  (10, 'trabajo', 'Antes de entregar un trabajo, revisa los datos y los detalles que más podrían causar problemas.'),
  (11, 'trabajo', 'Si cometiste un error, avisa pronto y explica qué puedes hacer para corregirlo.'),
  (12, 'trabajo', 'Pide ayuda cuando notes un problema que no puedes resolver. No esperes a que crezca.'),
  (13, 'trabajo', 'Cuando alguien haga bien su trabajo, dile qué hizo bien. Un reconocimiento concreto vale más que un elogio general.'),
  (14, 'trabajo', 'Si no estás de acuerdo, habla del problema y de una posible solución sin atacar a la persona.'),
  (15, 'trabajo', 'Anota cómo se hace una tarea que repites. Así será más fácil enseñarla o retomarla después.'),
  (16, 'trabajo', 'Cuando una tarea requiera atención, guarda el teléfono y evita las distracciones que puedas controlar.'),
  (17, 'trabajo', 'Termina una parte del trabajo antes de abrir otra, siempre que tus responsabilidades lo permitan.'),
  (18, 'trabajo', 'Para tareas con varios detalles, usa una lista corta y marca cada paso al completarlo.'),
  (19, 'trabajo', 'Antes de terminar tu jornada, deja anotado el siguiente paso de lo que quedó pendiente.'),
  (20, 'trabajo', 'Pide una sugerencia concreta para mejorar tu trabajo y elige una que puedas poner en práctica.'),
  (21, 'vida_personal', 'Cuando alguien te hable, escucha hasta el final antes de preparar tu respuesta.'),
  (22, 'vida_personal', 'Agradece una ayuda diciendo qué significó para ti. Un gracias con un motivo se siente más cercano.'),
  (23, 'vida_personal', 'Si necesitas disculparte, reconoce lo que hiciste y acompaña tus palabras con un cambio concreto.'),
  (24, 'vida_personal', 'Puedes decir que no con respeto. Explica tu límite sin prometer algo que no podrás cumplir.'),
  (25, 'vida_personal', 'Comparte un rato con alguien sin mirar el teléfono. Dale tu atención completa, aunque sea por unos minutos.'),
  (26, 'vida_personal', 'Escribe o llama a una persona que aprecias. No hace falta esperar una ocasión especial.'),
  (27, 'vida_personal', 'Di lo que necesitas con palabras claras. Las otras personas no siempre pueden adivinarlo.'),
  (28, 'vida_personal', 'Si estás muy molesto, pide una pausa y acuerda cuándo retomar la conversación.'),
  (29, 'vida_personal', 'Repartan las tareas de la casa con acuerdos claros y revisen si la carga está equilibrada.'),
  (30, 'vida_personal', 'Compara tu avance con tu propio punto de partida, no solo con lo que otras personas muestran.'),
  (31, 'vida_personal', 'Reconoce un pequeño logro de hoy. Los avances también cuentan cuando nadie más los ve.'),
  (32, 'vida_personal', 'Reserva un momento para una actividad que disfrutes y que no dependa de gastar dinero.'),
  (33, 'vida_personal', 'Antes de una conversación difícil, anota qué ocurrió, cómo te afectó y qué necesitas pedir.'),
  (34, 'vida_personal', 'Si algo que alguien dijo te molestó, pregunta qué quiso decir antes de sacar conclusiones.'),
  (35, 'vida_personal', 'Al hacer planes en grupo, pregunta por el tiempo y el presupuesto de las demás personas.'),
  (36, 'vida_personal', 'No tienes que responder de inmediato a todo mensaje. Date tiempo para pensar cuando haga falta.'),
  (37, 'vida_personal', 'Antes de compartir una foto o una historia de otra persona, pide su permiso.'),
  (38, 'vida_personal', 'Si vas a llegar tarde, avisa en cuanto lo sepas. El tiempo de los demás también importa.'),
  (39, 'vida_personal', 'Ofrece la ayuda que de verdad puedes dar, sin comprometer todo tu tiempo o tus recursos.'),
  (40, 'vida_personal', 'Cuando necesites apoyo, pide algo concreto: que te escuchen, te acompañen o te ayuden con una tarea.'),
  (41, 'finanzas', 'Anota lo que gastas durante una semana. Ver los gastos juntos ayuda a decidir qué ajustar.'),
  (42, 'finanzas', 'Haz una lista antes de comprar y revisa lo que ya tienes para evitar compras repetidas.'),
  (43, 'finanzas', 'Antes de comprar en cuotas, suma todos los pagos y los cargos. Mira el costo total, no solo la cuota.'),
  (44, 'finanzas', 'Si tu presupuesto lo permite, aparta una cantidad pequeña para ahorrar antes de gastar en cosas opcionales.'),
  (45, 'finanzas', 'Si una compra no es urgente, espera un día y revisa si todavía la necesitas.'),
  (46, 'finanzas', 'Revisa tus suscripciones y cancela las que ya no usas.'),
  (47, 'finanzas', 'Anota tus pagos fijos y sus fechas para saber cuánto dinero necesitas reservar.'),
  (48, 'finanzas', 'Al comparar productos de distinto tamaño, revisa el precio por unidad y cuánto vas a utilizar.'),
  (49, 'finanzas', 'Cuando recibas un ingreso, separa primero lo que necesitas para los gastos esenciales.'),
  (50, 'finanzas', 'Pon un recordatorio antes de la fecha de pago de tus recibos para evitar olvidos.'),
  (51, 'finanzas', 'Antes de contratar un servicio, pregunta por sus comisiones, cargos y condiciones de cancelación.'),
  (52, 'finanzas', 'Revisa los cobros de tu cuenta y de tu tarjeta. Si algo no coincide, consulta con la entidad.'),
  (53, 'finanzas', 'No compartas contraseñas ni códigos de verificación, aunque el mensaje parezca venir de tu banco.'),
  (54, 'finanzas', 'Antes de pagar, revisa las condiciones de garantía y devolución, especialmente en compras costosas.'),
  (55, 'finanzas', 'Guarda los comprobantes de pagos importantes en un lugar que puedas encontrar fácilmente.'),
  (56, 'finanzas', 'Planea varios mandados en una sola salida cuando sea posible y compara el costo del transporte.'),
  (57, 'finanzas', 'Para una meta de ahorro, escribe cuánto necesitas y para cuándo. Luego revisa cuánto podrías apartar.'),
  (58, 'finanzas', 'Si puedes, empieza una reserva para imprevistos con una cantidad que no afecte tus necesidades básicas.'),
  (59, 'finanzas', 'Si compartes gastos con alguien, acuerden cuánto aporta cada persona y cuándo se paga.'),
  (60, 'finanzas', 'No compres algo solo porque tiene descuento. Pregúntate si lo necesitas y si cabe en tu presupuesto.'),
  (61, 'aprendizaje', 'Dedica unos minutos a aprender algo que te dé curiosidad. Empieza con una pregunta pequeña.'),
  (62, 'aprendizaje', 'Después de aprender algo, explícalo con tus propias palabras para comprobar qué entendiste.'),
  (63, 'aprendizaje', 'Anota las preguntas que te surjan. Una duda escrita es más fácil de investigar después.'),
  (64, 'aprendizaje', 'Si estás aprendiendo una habilidad, practica con un ejemplo sencillo antes de intentar uno complicado.'),
  (65, 'aprendizaje', 'Antes de dar por cierto un dato importante, compáralo con otra fuente confiable.'),
  (66, 'aprendizaje', 'Cuando encuentres una palabra nueva, busca su significado y úsala en una frase propia.'),
  (67, 'aprendizaje', 'Repasa mañana una idea que aprendiste hoy, sin mirar primero tus apuntes.'),
  (68, 'aprendizaje', 'Elige una parte de la habilidad que quieres mejorar y practica esa parte por separado.'),
  (69, 'aprendizaje', 'Comparte algo que aprendiste con otra persona y escucha sus preguntas.'),
  (70, 'aprendizaje', 'Busca una ocasión pequeña para usar lo que estás aprendiendo en tu vida diaria.'),
  (71, 'aprendizaje', 'Al leer una noticia, revisa quién la publicó, de dónde salen los datos y de qué fecha es.'),
  (72, 'aprendizaje', 'Antes de pagar un curso, revisa si una biblioteca o una institución ofrece material gratuito sobre el tema.'),
  (73, 'aprendizaje', 'Si una explicación es demasiado difícil, busca otra que use un ejemplo cotidiano.'),
  (74, 'aprendizaje', 'Guarda una nota breve de lo que aprendiste y de lo que todavía necesitas practicar.'),
  (75, 'aprendizaje', 'Si te equivocas al practicar, identifica el paso que falló y vuelve a intentar solo esa parte.'),
  (76, 'aprendizaje', 'Haz preguntas sin disculparte por no saber. Aprender empieza por reconocer una duda.'),
  (77, 'aprendizaje', 'Lee un poco sobre un tema que normalmente no eliges. Puedes encontrar una idea útil fuera de tu rutina.'),
  (78, 'aprendizaje', 'Cuando sigas un tutorial, pausa y haz cada paso tú mismo en lugar de verlo todo de una vez.'),
  (79, 'aprendizaje', 'Para aprender de alguien con experiencia, pídele que explique cómo toma una decisión, no solo qué hace.'),
  (80, 'aprendizaje', 'Elige un momento pequeño y realista para practicar. Es más fácil mantener un hábito que sí cabe en tu día.'),
  (81, 'habitos', 'Deja las llaves y los objetos que usas a diario en el mismo lugar para encontrarlos sin buscar tanto.'),
  (82, 'habitos', 'Prepara la noche anterior una cosa que facilite tu mañana, como la ropa o lo que necesitas llevar.'),
  (83, 'habitos', 'Ordena un espacio pequeño en vez de intentar ordenar todo de una vez.'),
  (84, 'habitos', 'Al revisar tus pendientes, elige qué puedes hacer hoy y qué conviene dejar para otro momento.'),
  (85, 'habitos', 'Si quieres empezar un hábito, haz su primera versión muy pequeña para poder repetirla.'),
  (86, 'habitos', 'Deja a la vista lo que te ayude a cumplir una meta y guarda lo que te distraiga de ella.'),
  (87, 'habitos', 'Pon una alarma para una tarea importante que sueles olvidar, pero evita llenar el día de avisos.'),
  (88, 'habitos', 'Antes de aceptar otro compromiso, revisa si también te queda tiempo para descansar.'),
  (89, 'habitos', 'Haz una copia de los archivos importantes y comprueba que puedes abrirla.'),
  (90, 'habitos', 'Usa una contraseña diferente en cada cuenta y activa la verificación en dos pasos cuando esté disponible.'),
  (91, 'habitos', 'Si un mensaje te exige actuar de inmediato, verifica al remitente por otro medio antes de abrir enlaces o enviar datos.'),
  (92, 'habitos', 'Elige un cajón o una carpeta para guardar documentos importantes y revisa qué hace falta ordenar.'),
  (93, 'habitos', 'Antes de cocinar, revisa los alimentos que ya tienes y cuáles conviene usar primero.'),
  (94, 'habitos', 'Haz una lista corta de lo que necesitas llevar antes de una salida importante.'),
  (95, 'habitos', 'Cuando planees el día, deja un pequeño espacio para imprevistos en vez de llenar cada minuto.'),
  (96, 'habitos', 'Si dejaste un hábito unos días, retómalo con un paso pequeño. No hace falta compensarlo todo de golpe.'),
  (97, 'habitos', 'Revisa una vez por semana qué te está quitando tiempo y elige un cambio sencillo para probar.'),
  (98, 'habitos', 'Apaga una notificación que no te aporte nada. Recuperar atención también empieza con cambios pequeños.'),
  (99, 'habitos', 'Antes de desechar algo útil que ya no necesitas, revisa si puedes repararlo, reutilizarlo o donarlo.'),
  (100, 'habitos', 'Al terminar el día, elige una cosa que salió bien y una que quieres hacer diferente mañana.');

